export const IS_AUTHORIZATION = 'AUTH/IS_AUTHORIZATION'
export const IS_AUTHENTICATED = 'AUTH/IS_AUTHENTICATED'

export const SET_SUBSCRIPTIONS = 'CURRENT_USER/SET_DATA_USER_BLOG'
export const ADD_SUBSCRIPTIONS = 'CURRENT_USER/ADD_SUBSCRIPTIONS'
export const SET_PAGEBLOG = 'CURRENT_USER/ADD_PAGEBLOG'
export const SET_AVATAR = 'CURRENT_USER/SET_AVATAR'
export const UPDATE_USER_DATA = 'CURRENT_USER/UPDATE_USER_DATA'
export const UPDATE_ARRAY_DATA_USER = 'CURRENT_USER/UPDATE_ARRAY_DATA_USER'

export const SET_DATA_BLOG = 'BLOG/DATA_PAGE'
export const UPDATE_DATA_BLOG = 'BLOG/UPDATE_DATA_BLOG'
export const ADD_DATA_BLOG = 'BLOG/ADD_DATA_BLOG'
export const REMOVE_DATA_BLOG = 'BLOG/REMOVE_DATA_BLOG'
export const UPDATE_ARRAY_DATA_BLOG = 'BLOG/UPDATE_ARRAY_DATA_BLOG'

export const OPEN_DRAWER = 'APP/OPEN_DRAWER'

export enum EReduxActionTypes {
    IS_AUTHENTICATED = 'AUTH/IS_AUTHENTICATED',

    OPEN_DRAWER = 'APP/OPEN_DRAWER',

    SET_SUBSCRIPTIONS = 'CURRENT_USER/SET_DATA_USER_BLOG',
    ADD_SUBSCRIPTIONS = 'CURRENT_USER/ADD_SUBSCRIPTIONS',
    SET_PAGEBLOG = 'CURRENT_USER/ADD_PAGEBLOG',
    SET_AVATAR = 'CURRENT_USER/SET_AVATAR',
    UPDATE_USER_DATA = 'CURRENT_USER/UPDATE_USER_DATA',
    UPDATE_ARRAY_DATA_USER = 'CURRENT_USER/UPDATE_ARRAY_DATA_USER',

    SET_DATA_BLOG = 'BLOG/DATA_PAGE',
    UPDATE_DATA_BLOG = 'BLOG/UPDATE_DATA_BLOG',
    ADD_DATA_BLOG = 'BLOG/ADD_DATA_BLOG',
    REMOVE_DATA_BLOG = 'BLOG/REMOVE_DATA_BLOG',
    UPDATE_ARRAY_DATA_BLOG = 'BLOG/UPDATE_ARRAY_DATA_BLOG',

}

