export const IS_AUTHORIZATION = 'AUTH/IS_AUTHORIZATION'
export const IS_AUTHENTICATED = 'AUTH/IS_AUTHENTICATED'

export const SET_MY_PAGE = 'CURRENT_USER/MY_PAGE'

export const SET_DATA_BLOG = 'BLOG/DATA_PAGE'
