export const IS_AUTHORIZATION = 'AUTH/IS_AUTHORIZATION'
export const IS_AUTHENTICATED = 'AUTH/IS_AUTHENTICATED'

export const SET_SUBSCRIPTIONS = 'CURRENT_USER/SET_DATA_USER_BLOG'
export const ADD_SUBSCRIPTIONS = 'CURRENT_USER/ADD_SUBSCRIPTIONS'
export const SET_PAGEBLOG = 'CURRENT_USER/ADD_PAGEBLOG'

export const SET_DATA_BLOG = 'BLOG/DATA_PAGE'
export const UPDATE_DATA_BLOG = 'BLOG/UPDATE_DATA_BLOG'

export const OPEN_DRAWER = 'APP/OPEN_DRAWER'
